version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - mynetwork
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - mynetwork

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mynetwork
  kafdrop:
      image: obsidiandynamics/kafdrop:latest
      container_name: kafdrop
      ports:
        - "9000:9000"
      environment:
        KAFKA_BROKERCONNECT: kafka:9092
      depends_on:
        - kafka
      networks:
        - mynetwork

  # redpanda:
  #   image: vectorized/redpanda:latest
  #   container_name: redpanda
  #   ports:
  #     - "9092:9092"
  #     - "9644:9644"
  #   command:
  #     - redpanda
  #     - start
  #     - --smp
  #     - '1'
  #     - --memory
  #     - '2G'
  #     - --reserve-memory
  #     - '0M'
  #     - --overprovisioned
  #     - --node-id
  #     - '0'
  #     - --kafka-addr
  #     - 'PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092'
  #     - --advertise-kafka-addr
  #     - 'PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092'
  #   networks:
  #     - mynetwork
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - ./loki-config:/etc/loki
  #   command: -config.file=/etc/loki/loki-config.yaml
  #   networks:
  #     - mynetwork

  # promtail:
  #   image: grafana/promtail:latest
  #   container_name: promtail
  #   volumes:
  #     - ./promtail-config:/etc/promtail
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/log:/var/log:ro
  #   command: -config.file=/etc/promtail/promtail-config.yaml
  #   networks:
  #     - mynetwork

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     GF_SECURITY_ADMIN_USER: admin
  #     GF_SECURITY_ADMIN_PASSWORD: admin
  #   volumes:
  #     - ./grafana-data:/var/lib/grafana
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: bridge