---
- name: Запуск инфраструктуры
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Убедиться, что Docker установлен
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Убедиться, что служба Docker запущена
      service:
        name: docker
        state: started
        enabled: yes

    - name: Создать директорию проекта
      file:
        path: /home/server/PayBat
        state: directory
        mode: '0777'
        owner: server
        group: server

    - name: Создать директорию для данных базы данных
      file:
        path: /home/server/PayBat/database
        state: directory
        mode: '0777'
        owner: server
        group: server

    - name: Создать директорию для конфигурации Loki
      file:
        path: /home/server/PayBat/loki-config
        state: directory
        mode: '0777'
        owner: server
        group: server

    - name: Создать директорию для конфигурации Promtail
      file:
        path: /home/server/PayBat/promtail-config
        state: directory
        mode: '0777'
        owner: server
        group: server

    - name: Создать директорию для данных Grafana
      file:
        path: /home/server/PayBat/grafana-data
        state: directory
        mode: '0777'
        owner: server
        group: server

    - name: Скопировать файл Docker Compose
      copy:
        src: ./docker-compose.yaml
        dest: /home/server/PayBat/docker-compose.yaml
        owner: server
        group: server

    - name: Скопировать конфигурацию Loki
      copy:
        src: ./loki-config/loki-config.yaml
        dest: /home/server/PayBat/loki-config/loki-config.yaml
        owner: server
        group: server

    - name: Скопировать конфигурацию Promtail
      copy:
        src: ./promtail-config/promtail-config.yaml
        dest: /home/server/PayBat/promtail-config/promtail-config.yaml
        owner: server
        group: server
    
    - name: Проверить, запущены ли контейнеры
      command: sudo docker-compose ps
      args:
        chdir: /home/server/PayBat
      register: docker_ps_result
      ignore_errors: yes

    - name: Остановить Docker-контейнеры если они запущены
      command: sudo docker-compose stop
      args:
        chdir: /home/server/PayBat
      when: docker_ps_result.rc == 0

    - name: Запустить Docker-контейнеры
      command: docker-compose up --build -d
      args:
        chdir: /home/server/PayBat