name: Release Sync

on:
  push:
    branches:
      - '*-release'

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Switch to main branch
        run: |
          git checkout main

      - name: Run upload-app.sh script
        run: |
          chmod +x ./scripts/upload-app.sh
          ./scripts/upload-app.sh

      - name: Commit changes to main
        run: |
          git commit -m "Auto-update: Synced release branches to main"
          git push origin main